import { Box } from "@chakra-ui/react";
import Nav from "components/Nav";
import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <main>
      <Head>
        <title>Von Carcha - My Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <Nav />
      </Box>
    </main>
  );
};

export default Home;
