import { Box, Button, Heading } from '@chakra-ui/react';
import About from 'components/About';
import Nav from 'components/Nav';
import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <main>
      <Head>
        <title>Von Carcha - My Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <Box px={{ base: 4, md: 6 }} maxW="800px" w="100%" m="auto">
        <About />
        <Heading variant="section-title">Work</Heading>
      </Box>
    </main>
  );
};

export default Home;
