import Head from 'next/head';
import type { NextPage } from 'next';
import { Box } from '@chakra-ui/react';
import About from 'components/About';
import Education from 'components/Education';
import Experience from 'components/Experience';
import Header from 'components/Header';
import Portfolio from 'components/Portfolio';
import Skills from 'components/Skills';
import Nav from 'components/Nav';
import Contact from 'components/Contact';

const HomePage: NextPage = () => {
  return (
    <Box as="main">
      <Head>
        <title>Von Carcha - My Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box px={{ base: 4, md: 6 }} py={5} maxW="700px" w="100%" m="auto">
        <Nav />
        <Header />
        <About />
        <Portfolio />
        <Experience />
        <Education />
        <Skills />
        <Contact />
      </Box>
    </Box>
  );
};

export default HomePage;
