import { Box } from '@chakra-ui/react';
import Head from 'next/head';
import Header from 'components/Header';
import type { GetStaticPaths, GetStaticProps, NextPage } from 'next';
import Nav from 'components/Nav';
import Project from 'components/Project';
import { IPortfolio, PORTFOLIO } from 'common/constants';

interface Props {
  item: IPortfolio;
}

const ProjectPage: NextPage<Props> = ({ item }) => {
  return (
    <Box as="main">
      <Head>
        <title>Von Carcha - {item.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box px={{ base: 4, md: 6 }} py={5} maxW="700px" w="100%" m="auto">
        <Nav />
        <Header />
        <Project item={item}/>
      </Box>
    </Box>
  );
};

export const getStaticPaths: GetStaticPaths = async () => {
  const paths = PORTFOLIO.map((i) => {
    return {
      params: {
        slug: i.slug,
      },
    };
  });
  return {
    paths,
    fallback: false,
  };
};

export const getStaticProps: GetStaticProps = async ({ params }) => {
  const item = PORTFOLIO.find((i) => i.slug === params?.slug);

  return { props: { item } };
};

export default ProjectPage;
