import { Box } from '@chakra-ui/react';
import Head from 'next/head';
import Header from 'components/Header';
import Portfolio from 'components/Portfolio';
import type { NextPage } from 'next';
import Nav from 'components/Nav';

const PortfolioPage: NextPage = () => {
  return (
    <Box as="main">
      <Head>
        <title>Von Carcha - My Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box px={{ base: 4, md: 6 }} py={5} maxW="700px" w="100%" m="auto">
        <Nav />
        <Header />
        <Portfolio />
      </Box>
    </Box>
  );
};

export default PortfolioPage;
